### ISSUE TITLE
Error on startup: dependency missing?

### ISSUE THREAD

**Issue by pcav** [BioComputing/irods-qgis#1]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/paolo/Scrivania/butta/qgis_conf/python/plugins/irods_qgis/__init__.py", line 34, in classFactory
    from .irods_qgis import irods_qgis
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/Scrivania/butta/qgis_conf/python/plugins/irods_qgis/irods_qgis.py", line 29, in 
    from irods_qgis_dialog import irods_qgisDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/Scrivania/butta/qgis_conf/python/plugins/irods_qgis/irods_qgis_dialog.py", line 29, in 
    from irods.session import iRODSSession
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named irods.session

**Comment by pcav** [comment]
If a Py lib is necessary, this should be stated clearly in the About field, with instructions on how to install it.

**Comment by amit4111989** [comment]
The code was not updated on the qgis-repo, and it was still running a month old code. I updated the repo with latest code which resolves all the dependencies, and it should be working now
